import { Theme } from './types.ts';

export const themes: Theme[] = [
   {
    id: 'liquid-glass',
    name: 'Liquid Glass',
    colors: {
      '--color-bg-primary': 'rgba(255, 255, 255, 0.85)',
      '--color-bg-secondary': 'rgba(248, 249, 253, 0.92)',
      '--color-bg-tertiary': 'rgba(245, 245, 255, 0.95)',
      '--color-text-primary': '#000000',
      '--color-text-secondary': '#1a1a1a',
      '--color-text-muted': '#4a4a4a',
      '--color-border-primary': 'rgba(0, 0, 0, 0.1)',
      '--color-border-secondary': 'rgba(0, 0, 0, 0.05)',
      '--color-accent-primary': '#0984e3',
      '--color-accent-primary-hover': '#0097e6',
      '--color-accent-secondary': '#d63031',
    },
  },
  {
    id: 'classic-light',
    name: 'Classic Light',
    colors: {
      '--color-bg-primary': '#ffffff',
      '--color-bg-secondary': '#f8f9fa',
      '--color-bg-tertiary': '#f1f3f4',
      '--color-text-primary': '#202124',
      '--color-text-secondary': '#5f6368',
      '--color-text-muted': '#80868b',
      '--color-border-primary': '#dadce0',
      '--color-border-secondary': '#e0e0e0',
      '--color-accent-primary': '#1a73e8',
      '--color-accent-primary-hover': '#185abc',
      '--color-accent-secondary': '#e84393',
    },
  },
   {
    id: 'solar-flare',
    name: 'Solar Flare',
    colors: {
      '--color-bg-primary': '#1a0f00',
      '--color-bg-secondary': '#2e1c00',
      '--color-bg-tertiary': '#422800',
      '--color-text-primary': '#ffead6',
      '--color-text-secondary': '#ffc58a',
      '--color-text-muted': '#b38960',
      '--color-border-primary': '#5c3700',
      '--color-border-secondary': '#754600',
      '--color-accent-primary': '#ff8c00',
      '--color-accent-primary-hover': '#ffa533',
      '--color-accent-secondary': '#ff4500',
    },
  },
  {
    id: 'cyberpunk-glow',
    name: 'Cyberpunk Glow',
    colors: {
      '--color-bg-primary': '#0d0c1d',
      '--color-bg-secondary': '#1a1832',
      '--color-bg-tertiary': '#2c2a52',
      '--color-text-primary': '#e0e0e0',
      '--color-text-secondary': '#a9a8c3',
      '--color-text-muted': '#7e7d9b',
      '--color-border-primary': '#3a3862',
      '--color-border-secondary': '#4d4b7f',
      '--color-accent-primary': '#00f5d4', // Neon Cyan
      '--color-accent-primary-hover': '#9bfcf1', // Lighter Neon Cyan
      '--color-accent-secondary': '#ff00a0', // Neon Magenta
    },
  },
  {
    id: 'dark',
    name: 'Nordic Night',
    colors: {
      '--color-bg-primary': '#2e3440',
      '--color-bg-secondary': '#3b4252',
      '--color-bg-tertiary': '#434c5e',
      '--color-text-primary': '#eceff4',
      '--color-text-secondary': '#d8dee9',
      '--color-text-muted': '#a0a9b8',
      '--color-border-primary': '#4c566a',
      '--color-border-secondary': '#5d687e',
      '--color-accent-primary': '#88c0d0',
      '--color-accent-primary-hover': '#8fbcbb',
      '--color-accent-secondary': '#b48ead',
    },
  },
  {
    id: 'matrix',
    name: 'Matrix Green',
    colors: {
      '--color-bg-primary': '#020b05',
      '--color-bg-secondary': '#04160a',
      '--color-bg-tertiary': '#072b13',
      '--color-text-primary': '#34d399',
      '--color-text-secondary': '#6ee7b7',
      '--color-text-muted': '#a7f3d0',
      '--color-border-primary': '#064e3b',
      '--color-border-secondary': '#047857',
      '--color-accent-primary': '#10b981',
      '--color-accent-primary-hover': '#059669',
      '--color-accent-secondary': '#a7f3d0',
    },
  },
   {
    id: 'solarized',
    name: 'Solarized',
    colors: {
        '--color-bg-primary': '#002b36',
        '--color-bg-secondary': '#073642',
        '--color-bg-tertiary': '#586e75',
        '--color-text-primary': '#93a1a1',
        '--color-text-secondary': '#839496',
        '--color-text-muted': '#657b83',
        '--color-border-primary': '#586e75',
        '--color-border-secondary': '#657b83',
        '--color-accent-primary': '#268bd2',
        '--color-accent-primary-hover': '#2aa198',
        '--color-accent-secondary': '#d33682',
    },
  },
];